### ISSUE TITLE
I don't know if I did something wrong but it literally just doesn't work.

### ISSUE THREAD

**Issue by krxma** [livrasand/YouTubePremiumFree#1]
It literally doesn't work

**Comment by livrasand** [comment]
Hi, thank you very much for your feedback, I use it every day on 3 different devices and it works like a charm. Did you follow the installation steps correctly? Can you share a screenshot of your problem?

**Comment by Aeyoub-777** [comment]
It didn't work for me I followed all steps, yet it doesn't work.
There's a chance I might have done something wrong who knows, 
kindly hope you make a tutorial video installing it

**Comment by livrasand** [comment]
Thank you very much for the report, I will make a video now, but really the installation should not fail.

**Comment by livrasand** [comment]
One question, what web browser are you using?

**Comment by krxma** [comment]
i got it to work
